### ISSUE TITLE
soname moved backwards?

### ISSUE THREAD

**Issue by leahneukirchen** [NLnetLabs/ldns#146] opened 2021-11-27 13:52 UTC
ldns 1.7.1 had /usr/lib/libldns.so.3.0.0
ldns 1.8.0 has /usr/lib/libldns.so.2.2.0

Is this intentional? What does it mean?

**Comment by wtoorop** [comment] 2021-11-29 20:39
No it is an error (caused by a typo in the 1.7.1 release).  Note that the number on line 30 and 32 of configure.ac don't match in the 1.7.1 release: https://github.com/NLnetLabs/ldns/blob/release-1.7.1/configure.ac#L30 . This caused ldns-1.7.1 to wrongly bump to .so.3.  I will do a 1.8.1 release shortly to correct this.

**Comment by leahneukirchen** [comment] 2021-11-29 20:46
Thank you!

**Comment by wtoorop** [comment] 2021-12-27 15:11
Resolved in ldns 1.8.1.

**Closed by wtoorop** 2021-12-27 15:11 UTC
