### ISSUE TITLE
Introduce +short option to drill

### ISSUE THREAD

**Issue by dilyanpalauzov** [NLnetLabs/ldns#56] opened 2019-11-20 07:30 UTC
https://github.com/matteocorti/check_ssl_cert can if the TLSA records match the offered certificate (DANE) and can obtain the TLSA records using “dig +short” or “delv +short”.  To be able to use a different resolver, like “drill -D” or “drill -DT” that uses the same output/input format, please introduce option `+short` to drill.

**Comment by reedjc** [comment] 2019-12-12 03:33
This is a duplicate of #28 .

**Closed** 2019-12-12 06:34 UTC
