### ISSUE TITLE
Homebrew install fails under MacOS Catalina 10.15

### ISSUE THREAD

**Issue by selfagency** [NLnetLabs/ldns#16] opened 2019-06-07 19:36 UTC
```
selfagency-macpro:~ daniel$ brew install ldns --HEAD
Updating Homebrew...

==> Downloading https://nlnetlabs.nl/downloads/ldns/ldns-1.7.0.tar.gz
Already downloaded: /Users/daniel/Library/Caches/Homebrew/downloads/95bb5b8984276f4dd8d6ce135b473e8a28545114332949a45e98d840d8f1626b--ldns-1.7.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/ldns/1.7.0_1 --with-drill --with-examples --with-ssl=/usr/local/opt/openssl --with-pyldns PYTHON_SITE_PKG=/usr/local/Cellar/ldns/1.7.0_1/lib/python2.7/site-packages --disable-dane-verify
==> make
Last 15 lines from /Users/daniel/Library/Logs/Homebrew/ldns/02.make:
./libtool --tag=CC --quiet --mode=link clang -Wunused-function -Wstrict-prototypes -Wwrite-strings -W -Wall -g -O2 -mmacosx-version-min=10.10 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk  -L/usr/local/opt/openssl/lib examples/ldns-dpa.lo  -lpcap -lldns \
		 -o examples/ldns-dpa
./libtool --tag=CC --quiet --mode=link clang -Wunused-function -Wstrict-prototypes -Wwrite-strings -W -Wall -g -O2 -mmacosx-version-min=10.10 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk  -L/usr/local/opt/openssl/lib examples/ldns-dane.lo  -lssl  -lcrypto -lldns \
		 -o examples/ldns-dane
./libtool --tag=CC --quiet --mode=link clang -Wunused-function -Wstrict-prototypes -Wwrite-strings -W -Wall -g -O2 -mmacosx-version-min=10.10 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk  -L/usr/local/opt/openssl/lib examples/ldns-nsec3-hash.lo  -lcrypto -lldns -o examples/ldns-nsec3-hash
./libtool --tag=CC --quiet --mode=link clang -Wunused-function -Wstrict-prototypes -Wwrite-strings -W -Wall -g -O2 -mmacosx-version-min=10.10 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk  -L/usr/local/opt/openssl/lib examples/ldns-revoke.lo  -lcrypto -lldns -o examples/ldns-revoke
./libtool --tag=CC --quiet --mode=link clang -Wunused-function -Wstrict-prototypes -Wwrite-strings -W -Wall -g -O2 -mmacosx-version-min=10.10 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk  -L/usr/local/opt/openssl/lib examples/ldns-signzone.lo  -lcrypto -lldns -o examples/ldns-signzone
./libtool --tag=CC --quiet --mode=link clang -Wunused-function -Wstrict-prototypes -Wwrite-strings -W -Wall -g -O2 -mmacosx-version-min=10.10 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk  -L/usr/local/opt/openssl/lib examples/ldns-verify-zone.lo  -lcrypto -lldns -o examples/ldns-verify-zone
./libtool --tag=CC --quiet --mode=link clang -Wunused-function -Wstrict-prototypes -Wwrite-strings -W -Wall -g -O2 -mmacosx-version-min=10.10 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk  -L/usr/local/opt/openssl/lib linktest.lo  -lcrypto -lldns -o linktest
./libtool --tag=CC --quiet --mode=compile clang -I. -I.  -DHAVE_CONFIG_H -DLDNS_TRUST_ANCHOR_FILE="\"/usr/local/Cellar/ldns/1.7.0_1/etc/unbound/root.key\"" -Wunused-function -Wstrict-prototypes -Wwrite-strings -W -Wall -g -O2 -mmacosx-version-min=10.10 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I./include/ldns -I/usr/local/opt/openssl/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -Wno-unused-variable -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -c ./contrib/python/ldns_wrapper.c -o ldns_wrapper.lo
./contrib/python/ldns_wrapper.c:37536:51: error: use of undeclared identifier 'obj1'
  ldns_key_set_pubkey_owner(arg1,arg2); Py_INCREF(obj1);
                                                  ^
1 error generated.
make: *** [ldns_wrapper.lo] Error 1
```

**Comment by sukucorp** [comment] 2019-06-29 15:12
Same error on macOS 10.14 Mojave.

**Comment by wtoorop** [comment] 2019-07-11 09:35
The problem is the newer version of swig (i.e. 4.0). Duplicate of #7

**Closed by wtoorop** 2019-07-11 09:35 UTC
